service: swell-private

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: POst
  bye:
    handler: handler.bye
    events:
      - http:
          path: bye
          method: post
